# Generated by Django 3.1.4 on 2021-01-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createBy', models.IntegerField(verbose_name='创建人员')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updateBy', models.IntegerField(verbose_name='更新人员')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='迭代名称')),
                ('leader', models.IntegerField(verbose_name='迭代负责人')),
                ('description', models.CharField(max_length=256, verbose_name='迭代描述')),
            ],
            options={
                'verbose_name': '迭代',
                'verbose_name_plural': '迭代信息',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createBy', models.IntegerField(verbose_name='创建人员')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updateBy', models.IntegerField(verbose_name='更新人员')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('leader', models.IntegerField(verbose_name='项目负责人')),
                ('description', models.CharField(max_length=256, verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目信息',
            },
        ),
    ]
