# Generated by Django 3.1.4 on 2021-01-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('createBy', models.IntegerField(verbose_name='创建人员')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updateBy', models.IntegerField(verbose_name='更新人员')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('user', models.IntegerField(verbose_name='执行者')),
                ('tag', models.CharField(max_length=64, verbose_name='标签')),
                ('desc', models.CharField(max_length=1024, verbose_name='描述')),
                ('projectID', models.IntegerField(verbose_name='项目ID')),
                ('iterationID', models.IntegerField(verbose_name='迭代ID')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务信息',
            },
        ),
        migrations.RenameField(
            model_name='iteration',
            old_name='description',
            new_name='desc',
        ),
    ]
