# Generated by Django 3.1.4 on 2021-01-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210106_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='desc',
        ),
    ]
