# Generated by Django 3.1.4 on 2021-01-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210106_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='projectID',
        ),
        migrations.AddField(
            model_name='iteration',
            name='projectID',
            field=models.IntegerField(default=1, verbose_name='项目ID'),
            preserve_default=False,
        ),
    ]
