# Generated by Django 3.1.4 on 2021-01-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='createBy',
            field=models.IntegerField(default=None, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='updateBy',
            field=models.IntegerField(default=None, verbose_name='更新人员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='createBy',
            field=models.IntegerField(default=None, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updateBy',
            field=models.IntegerField(default=None, verbose_name='更新人员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='createBy',
            field=models.IntegerField(default=None, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updateBy',
            field=models.IntegerField(default=None, verbose_name='更新人员'),
        ),
    ]
